### ISSUE TITLE
Failed to get position details for Ethereum mainnet position id 615284

### ISSUE THREAD

**Issue by gnarlycow** [Aperture-Finance/Aperture-Lens#6]
Found an interesting failure case:
`await getPositionDetails(chainInfo.uniswap_v3_nonfungible_position_manager, 615284n, client, BLOCK_NUMBER);` failing with

> /Users/gnarlycow/dev/Analytics/node_modules/viem/utils/data/slice.ts:68
>     throw new SliceOffsetOutOfBoundsError({
>           ^
> SliceOffsetOutOfBoundsError: Slice ending at offset "64" is out-of-bounds (size: 4).
> 
> Version: viem@1.21.1
>     at assertEndOffset (/Users/gnarlycow/dev/Analytics/node_modules/viem/utils/data/slice.ts:68:11)
>     at sliceHex (/Users/gnarlycow/dev/Analytics/node_modules/viem/utils/data/slice.ts:122:15)
>     at slice (/Users/gnarlycow/dev/Analytics/node_modules/viem/utils/data/slice.ts:35:12)
>     at decodeParam (/Users/gnarlycow/dev/Analytics/node_modules/viem/utils/abi/decodeAbiParameters.ts:141:22)
>     at decodeTuple (/Users/gnarlycow/dev/Analytics/node_modules/viem/utils/abi/decodeAbiParameters.ts:371:26)
>     at decodeParam (/Users/gnarlycow/dev/Analytics/node_modules/viem/utils/abi/decodeAbiParameters.ts:132:12)
>     at decodeParams (/Users/gnarlycow/dev/Analytics/node_modules/viem/utils/abi/decodeAbiParameters.ts:94:33)
>     at decodeAbiParameters (/Users/gnarlycow/dev/Analytics/node_modules/viem/utils/abi/decodeAbiParameters.ts:66:10)
>     at decodeFunctionResult (/Users/gnarlycow/dev/Analytics/node_modules/viem/utils/abi/decodeFunctionResult.ts:89:37)
>     at callEphemeralContract (/Users/gnarlycow/dev/Analytics/node_modules/aperture-lens/dist/src/viem/caller.js:24:56) {
>   details: undefined,
>   docsPath: undefined,
>   metaMessages: undefined,
>   shortMessage: 'Slice ending at offset "64" is out-of-bounds (size: 4).',
>   version: 'viem@1.21.1'
> }

This seems to be only position id out of all 574551 positions that is having issues.

**Comment by shuhuiluo** [comment]
```Solidity
0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000294552433732313a206f776e657220717565727920666f72206e6f6e6578697374656e7420746f6b656e0000000000000000000000000000000000000000000000
Error("ERC721: owner query for nonexistent token")
```

**Comment by shuhuiluo** [comment]
[It](https://etherscan.io/nft/0xC36442b4a4522E871399CD717aBDD847Ab11FE88/615284) was minted at block [18690949](https://etherscan.io/tx/0x2ec172b60f8de8bb05917ee9c1c08c51765984c754bb54340dc5d87e6bc3c888).
