### ISSUE TITLE
Set up CARGO_REGISTRY_TOKEN and publish to crates.io

### ISSUE THREAD

**Issue by gnarlycow** [Aperture-Finance/Aperture-Lens#8]

**Comment by gnarlycow** [comment]
@shuhuiluo Do you want to commit the generated bindings (need to update .gitignore), or pass `--allow-dirty` to `cargo publish`?

> Run cargo publish
>     Updating crates.io index
> error: 54 files in the working directory contain changes that were not yet committed into git:
> 
> src/bindings/ephemeral_get_positions.rs
> src/bindings/ephemeral_all_positions_by_owner.rs
> src/bindings/ephemeral_get_position.rs
> src/bindings/i_nonfungible_position_manager.rs
> src/bindings/tick_bitmap.rs
> src/bindings/pool_utils.rs
> src/bindings/i_uniswap_v3_pool_state.rs
> src/bindings/i_uniswap_v3_swap_callback.rs
> src/bindings/ephemeral_storage_lens.rs
> src/bindings/ierc721.rs
> src/bindings/ierc721_enumerable.rs
> src/bindings/lib_bit.rs
> src/bindings/ierc721_token_receiver.rs
> src/bindings/position_utils.rs
> src/bindings/tick_math.rs
> src/bindings/shared_types.rs
> src/bindings/safe_cast.rs
> src/bindings/ierc721_permit.rs
> src/bindings/i_uniswap_v3_pool_derived_state.rs
> src/bindings/unsafe_math.rs
> src/bindings/erc20_caller.rs
> src/bindings/ephemeral_pool_tick_bitmap.rs
> src/bindings/mod.rs
> src/bindings/ephemeral_pool_positions.rs
> src/bindings/mock_erc721.rs
> src/bindings/ierc20.rs
> src/bindings/npm_caller.rs
> src/bindings/pool_address.rs
> src/bindings/ephemeral_pool_ticks.rs
> src/bindings/liquidity_amounts.rs
> src/bindings/i_periphery_payments.rs
> src/bindings/i_uniswap_v3_pool.rs
> src/bindings/bit_math.rs
> src/bindings/ternary_lib.rs
> src/bindings/i_uniswap_v3_pool_actions.rs
> src/bindings/i_uniswap_v3_pool_owner_actions.rs
> src/bindings/fixed_point_96.rs
> src/bindings/ierc721_metadata.rs
> src/bindings/i_uniswap_v3_pool_immutables.rs
> src/bindings/i_pool_initializer.rs
> src/bindings/i_uniswap_v3_factory.rs
> src/bindings/full_math.rs
> src/bindings/i_uniswap_v3_pool_events.rs
> src/bindings/ephemeral_pool_slots.rs
> src/bindings/i_periphery_immutable_state.rs
> src/bindings/ierc165.rs
> src/bindings/i_uniswap_v3_mint_callback.rs
> src/bindings/safe_transfer_lib.rs
> src/bindings/position_lens.rs
> src/bindings/ephemeral_get_populated_ticks_in_range.rs
> src/bindings/fixed_point_math_lib.rs
> src/bindings/ierc20_metadata.rs
> src/bindings/pool_caller.rs
> src/bindings/mock_erc20.rs
> 
> to proceed despite this and include the uncommitted changes, pass the `--allow-dirty` flag

**Comment by shuhuiluo** [comment]
> @shuhuiluo Do you want to commit the generated bindings (need to update .gitignore), or pass `--allow-dirty` to `cargo publish`?
> 
> > Run cargo publish
> > Updating crates.io index
> > error: 54 files in the working directory contain changes that were not yet committed into git:
> > src/bindings/ephemeral_get_positions.rs
> > src/bindings/ephemeral_all_positions_by_owner.rs
> > src/bindings/ephemeral_get_position.rs
> > src/bindings/i_nonfungible_position_manager.rs
> > src/bindings/tick_bitmap.rs
> > src/bindings/pool_utils.rs
> > src/bindings/i_uniswap_v3_pool_state.rs
> > src/bindings/i_uniswap_v3_swap_callback.rs
> > src/bindings/ephemeral_storage_lens.rs
> > src/bindings/ierc721.rs
> > src/bindings/ierc721_enumerable.rs
> > src/bindings/lib_bit.rs
> > src/bindings/ierc721_token_receiver.rs
> > src/bindings/position_utils.rs
> > src/bindings/tick_math.rs
> > src/bindings/shared_types.rs
> > src/bindings/safe_cast.rs
> > src/bindings/ierc721_permit.rs
> > src/bindings/i_uniswap_v3_pool_derived_state.rs
> > src/bindings/unsafe_math.rs
> > src/bindings/erc20_caller.rs
> > src/bindings/ephemeral_pool_tick_bitmap.rs
> > src/bindings/mod.rs
> > src/bindings/ephemeral_pool_positions.rs
> > src/bindings/mock_erc721.rs
> > src/bindings/ierc20.rs
> > src/bindings/npm_caller.rs
> > src/bindings/pool_address.rs
> > src/bindings/ephemeral_pool_ticks.rs
> > src/bindings/liquidity_amounts.rs
> > src/bindings/i_periphery_payments.rs
> > src/bindings/i_uniswap_v3_pool.rs
> > src/bindings/bit_math.rs
> > src/bindings/ternary_lib.rs
> > src/bindings/i_uniswap_v3_pool_actions.rs
> > src/bindings/i_uniswap_v3_pool_owner_actions.rs
> > src/bindings/fixed_point_96.rs
> > src/bindings/ierc721_metadata.rs
> > src/bindings/i_uniswap_v3_pool_immutables.rs
> > src/bindings/i_pool_initializer.rs
> > src/bindings/i_uniswap_v3_factory.rs
> > src/bindings/full_math.rs
> > src/bindings/i_uniswap_v3_pool_events.rs
> > src/bindings/ephemeral_pool_slots.rs
> > src/bindings/i_periphery_immutable_state.rs
> > src/bindings/ierc165.rs
> > src/bindings/i_uniswap_v3_mint_callback.rs
> > src/bindings/safe_transfer_lib.rs
> > src/bindings/position_lens.rs
> > src/bindings/ephemeral_get_populated_ticks_in_range.rs
> > src/bindings/fixed_point_math_lib.rs
> > src/bindings/ierc20_metadata.rs
> > src/bindings/pool_caller.rs
> > src/bindings/mock_erc20.rs
> > to proceed despite this and include the uncommitted changes, pass the `--allow-dirty` flag

Prefer `--allow-dirty`.

**Comment by gnarlycow** [comment]
https://crates.io/crates/aperture-lens
